language: python
python:
- '2.6'
- '2.7'
install:
- pip install .
- pip install coveralls
script: coverage run --source=pyorbital setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: Martin.Raspaud
  password:
    secure: ghpr9u0Pa79QPAFzovGKKqW48mf7bUtgcOBj7kgJ+e+HWnowqwtWsLmfMyJb4sq36bHBvMndCpgeM1UodM/7JeJn5V3jD6ISCjRUjog/S6o18ZFfl5y0s0s7ldpPLhl3/PF4hs+CNHJU5NMELzctsVIKqwnAOgB1PKgcHZ8WXUI=
  on:
    tags: true
    repo: mraspaud/pyorbital
